# Generated by Django 4.2.13 on 2025-05-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='emotion',
            field=models.CharField(blank=True, choices=[('happy', '😊'), ('neutral', '😐'), ('sad', '☹️')], max_length=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='emotion',
            field=models.CharField(blank=True, choices=[('happy', '😊'), ('neutral', '😐'), ('sad', '☹️')], max_length=10),
        ),
    ]
