# Generated by Django 4.2.13 on 2025-05-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_monthlybudget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedexpense',
            name='date',
        ),
        migrations.AddField(
            model_name='fixedexpense',
            name='day',
            field=models.PositiveIntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixedexpense',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
